export const TRENDS_RESET = 'TRENDS_RESET';

export const TRENDS_FETCH_REQUEST = 'TRENDS_FETCH_REQUEST';
export const TRENDS_FETCH_SUCCESS = 'TRENDS_FETCH_SUCCESS';
export const TRENDS_FETCH_FAILURE = 'TRENDS_FETCH_FAILURE';
