export const RESET_TRENDS = 'RESET_TRENDS';

export const FETCH_TRENDS_LOADING = 'FETCH_TRENDS_LOADING';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_FAILURE = 'FETCH_TRENDS_FAILURE';
